[package]
name = "ic_siwb"
version = "0.0.1"
edition = "2021"
authors = ["Ghostcorn <ghostcorn@astrox.network>"]
description = "."
license = "MIT"
homepage = "https://github.com/AstroxNetwork/ic-siwb"
repository = "https://github.com/AstroxNetwork/ic-siwb"


[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.66"
serde_bytes = "0.11"
serde_cbor = "0.11"
candid = "0.9.11"
hex = "0.4.3"
ic-cdk = "0.11.3"
ic-cdk-timers = { version = "0.5.1", optional = true }
icrc-ledger-types = "0.1.4"
ic-certified-map = "0.4.0"
url = "2.4.1"
time = { version = "0.3.30", features = ["formatting"] }
rand_chacha = { version = "0.3.1", optional = true }
getrandom = { version = "0.2.10", features = ["custom"] }
k256 = { version = "0.13.2", default-features = false, features = [
    "ecdsa",
    "sha256",
    "pem",
] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = "0.9.1"
simple_asn1 = "0.6.2"
bitcoin = { version = "0.30.2", features = ["serde", "base64"] }
byteorder = "1.5.0"
base64 = "0.22.1"

[dev-dependencies]
tokio = { version = "1.13.0", features = ["full"] }
rand = "0.8.4"
hex-literal = "0.2.1"

[features]
nonce = ["rand_chacha", "ic-cdk-timers"]
